# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_streaming.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61udio_streaming.proto\x12\x0f\x61udio_streaming\"\x1b\n\nAudioChunk\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\x32\\\n\rAudioStreamer\x12K\n\x0bStreamAudio\x12\x1b.audio_streaming.AudioChunk\x1a\x1b.audio_streaming.AudioChunk(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_streaming_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIOCHUNK._serialized_start=42
  _AUDIOCHUNK._serialized_end=69
  _AUDIOSTREAMER._serialized_start=71
  _AUDIOSTREAMER._serialized_end=163
# @@protoc_insertion_point(module_scope)
