# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio_stream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61udio_stream.proto\x12\x0c\x61udio_stream\x1a\x1bgoogle/protobuf/empty.proto\" \n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x32R\n\rAudioStreamer\x12\x41\n\x0bStreamAudio\x12\x18.audio_stream.AudioChunk\x1a\x16.google.protobuf.Empty(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_stream_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUDIOCHUNK._serialized_start=65
  _AUDIOCHUNK._serialized_end=97
  _AUDIOSTREAMER._serialized_start=99
  _AUDIOSTREAMER._serialized_end=181
# @@protoc_insertion_point(module_scope)
